---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://trmnl.bettens.dev/trending-recipes/trending?timeframe={{timeframe}}&limit=50&utc_offset={{trmnl.user.utc_offset}}{% if trmnl.plugin_settings.custom_fields_values.only_mine == "true" %}&user_id={{trmnl.user.id}}{%endif%}
polling_headers: ''
polling_body: ''
id: 240070
custom_fields:
- keyname: author_bio
  field_type: author_bio
  name: About This Plugin
- keyname: timeframe
  field_type: select
  name: Timeframe
  default: 24h
  options:
  - Today: today
  - 24h: 24h
- keyname: only_mine
  field_type: boolean
  name: Show only my recipes
  default: false
  optional: true
name: Trending Recipes
refresh_interval: 15
