---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://trmnl.bettens.dev/trending-recipes/trending?timeframe={{timeframe}}&limit=50&utc_offset={{trmnl.user.utc_offset}}{% if trmnl.plugin_settings.custom_fields_values.view_mode == "user" %}&user_id={{trmnl.user.id}}&include_unchanged=false{% elsif trmnl.plugin_settings.custom_fields_values.view_mode == "user_all" %}&user_id={{trmnl.user.id}}&include_unchanged=true{% endif %}
polling_headers: ''
polling_body: ''
id: 240070
custom_fields:
- keyname: author_bio
  field_type: author_bio
  name: About This Plugin
- keyname: timeframe
  field_type: select
  name: Timeframe
  default: 24h
  options:
  - Today: today
  - 24h: 24h
  - 3 Days: 3d
  - 7 Days: 7d
  - 30 Days: 30d
- keyname: view_mode
  field_type: select
  name: View Mode
  default: public
  options:
  - Public: public
  - Mine + Public: user
  - Mine (all) + Public: user_all
name: Trending Recipes
refresh_interval: 15
